<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; color: #333; margin: 0; padding: 0; background: #f4f4f4; }
        .wrapper { max-width: 960px; margin: 30px auto; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
        .header { background: #1e40af; color: #fff; padding: 28px 32px; }
        .header h1 { margin: 0; font-size: 22px; }
        .header p { margin: 6px 0 0; font-size: 14px; opacity: 0.85; }
        .body { padding: 28px 32px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 14px; }
        th { background: #f1f5f9; text-align: left; padding: 10px 12px; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; border-bottom: 2px solid #e2e8f0; }
        td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        tr:last-child td { border-bottom: none; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 12px; font-weight: 600; }
        .mu { background: #ede9fe; color: #6d28d9; }
        .nonmu { background: #dbeafe; color: #1d4ed8; }
        .submitted { background: #dcfce7; color: #15803d; }
        .open { background: #fef9c3; color: #a16207; }
        .total-row td { font-weight: bold; background: #f8fafc; }
        .footer { padding: 16px 32px; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
    </style>
</head>
<body>
<div class="wrapper">
    <div class="header">
        <h1>Workload Report</h1>
        <p>{{ ucfirst($period) }} report &mdash; {{ $periodLabel }}</p>
    </div>

    <div class="body">
        <p style="margin-top:0; color:#475569; font-size:14px;">
            Here is the workload summary for all estimators during <strong>{{ $periodLabel }}</strong>.
        </p>

        <table>
            <thead>
                <tr>
                    <th>Estimator</th>
                    <th>Total Jobs</th>
                    <th>Total Days</th>
                    <th>MU</th>
                    <th>NON MU</th>
                    <th>Submitted</th>
                    <th>Open</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reportData as $row)
                    <tr>
                        <td>
                            <strong>{{ $row['estimator']->name }}</strong><br>
                            <span style="font-size:12px; color:#94a3b8;">{{ ucfirst(str_replace('_', ' ', $row['estimator']->role)) }}</span>
                        </td>
                        <td><strong>{{ $row['total_jobs'] }}</strong></td>
                        <td><strong>{{ $row['total_days'] }}d</strong></td>
                        <td>
                            <span class="badge mu">{{ $row['mu_jobs'] }} jobs</span><br>
                            <span style="font-size:12px; color:#6d28d9;">{{ $row['mu_days'] }}d</span>
                        </td>
                        <td>
                            <span class="badge nonmu">{{ $row['non_mu_jobs'] }} jobs</span><br>
                            <span style="font-size:12px; color:#1d4ed8;">{{ $row['non_mu_days'] }}d</span>
                        </td>
                        <td><span class="badge submitted">{{ $row['submitted_jobs'] }}</span></td>
                        <td><span class="badge open">{{ $row['open_jobs'] }}</span></td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" style="text-align:center; color:#94a3b8; padding: 24px;">No data for this period.</td>
                    </tr>
                @endforelse

                @if($reportData->isNotEmpty())
                    <tr class="total-row">
                        <td>Total</td>
                        <td>{{ $reportData->sum('total_jobs') }}</td>
                        <td>{{ $reportData->sum('total_days') }}d</td>
                        <td>{{ $reportData->sum('mu_jobs') }} / {{ $reportData->sum('mu_days') }}d</td>
                        <td>{{ $reportData->sum('non_mu_jobs') }} / {{ $reportData->sum('non_mu_days') }}d</td>
                        <td>{{ $reportData->sum('submitted_jobs') }}</td>
                        <td>{{ $reportData->sum('open_jobs') }}</td>
                    </tr>
                @endif
            </tbody>
        </table>
    </div>

    <div class="footer">
        This is an automated report generated by the Bid Project system.
    </div>
</div>
</body>
</html>
